before:
  hooks:
    - go generate ./...
    - go mod download
builds:
- env:
  - CGO_ENABLED=0
  - GO111MODULE=on
  binary: phoneinfoga
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - 386
    - amd64
    - arm
    - arm64
  ldflags: -s -w -X gopkg.in/sundowndev/phoneinfoga.v2/config.Version={{.Version}} -X gopkg.in/sundowndev/phoneinfoga.v2/config.Commit={{.ShortCommit}}
archives:
- name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  files:
    - none*
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^chore:'
    - '^ci:'
    - Merge pull request
    - Merge branch
